export const departmentNames = [
  'General care',
  'Pediatrics',
  'Cardiology',
  'Oncology',
  'Orthopedics',
  'Neurology',
  'Dermatology',
  'Gynecology',
  'Urology',
  'ENT',
  'Ophthalmology',
  'Radiology',
  'Psychiatry',
  'Dentistry',
  'Emergency Medicine',
  'Anesthesiology',
  'Surgery',
  'Nephrology',
  'Gastroenterology',
  'Pulmonology',
  'Endocrinology',
  'Rheumatology',
  'Hematology',
  'Infectious Disease',
  'Geriatrics',
  'Physical Therapy',
  'Occupational Therapy',
  'Dietetics',
  'Speech Therapy',
  'Radiation Oncology',
];
